---
engines:
  coverage:
    exclude_paths:
      - ".github/**/*"
      - "build/**/*"
      - "CHANGELOG.md"
      - "README.md"
      - "omnisharp.json"
      - "stylecop.json"
      - "global.json"

exclude_paths:
  - "build/packages/**/*"